name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Run tests with coverage
      run: bun run test --run --coverage
      
    - name: Generate coverage badge
      run: |
        echo "📊 Coverage Analysis"
        echo "==================="
        
        # Parse coverage from vitest output
        if [ -f "coverage/coverage-summary.json" ]; then
          COVERAGE=$(cat coverage/coverage-summary.json | grep -o '"pct":[0-9]*' | head -1 | cut -d':' -f2)
          echo "Coverage: ${COVERAGE}%"
          echo "COVERAGE_PERCENT=${COVERAGE}" >> $GITHUB_ENV
          
          if [ $COVERAGE -ge 90 ]; then
            echo "✅ Coverage is above 90%"
            echo "COVERAGE_COLOR=brightgreen" >> $GITHUB_ENV
          elif [ $COVERAGE -ge 80 ]; then
            echo "⚠️ Coverage is above 80%"
            echo "COVERAGE_COLOR=yellow" >> $GITHUB_ENV
          else
            echo "❌ Coverage is below 80%"
            echo "COVERAGE_COLOR=red" >> $GITHUB_ENV
          fi
        else
          echo "❌ No coverage report found"
          echo "COVERAGE_PERCENT=0" >> $GITHUB_ENV
          echo "COVERAGE_COLOR=red" >> $GITHUB_ENV
        fi
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info
        fail_ci_if_error: false
        verbose: true
        
    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const coverage = process.env.COVERAGE_PERCENT;
          const color = process.env.COVERAGE_COLOR;
          let emoji = '✅';
          
          if (color === 'red') emoji = '❌';
          else if (color === 'yellow') emoji = '⚠️';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${emoji} **Coverage Report**\n\nCurrent coverage: **${coverage}%**\nTarget: 90%+`
          });